name: CI Pipeline

on:
  push:
  #Habilita o gatilho manual através da interface do Github Actions
  workflow_dispatch:

jobs:
  #Job para execução de testes
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    #Configuração de passos do nosso job
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK@17
        uses: actions/setuo-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run application tests
        run: ./gradlew test

